; PlatformIO Project Configuration File для примера i2c_scanner
;
; Пример использует библиотеку I2C-CH32V003 через lib_extra_dirs,
; указывающий на корень репозитория (на два уровня выше examples/i2c_scanner).

[env:ch32v003]
platform = ch32v
board = genericCH32V003F4P6
framework = noneos-sdk
lib_extra_dirs = ../../..
monitor_speed = 115200
