; PlatformIO Project Configuration File для примера i2c_scanner

[env:ch32v003]
platform = ch32v
board = genericCH32V003F4P6
framework = noneos-sdk
lib_deps =
    symlink://../..
monitor_speed = 115200
